package dev.oillamp;

import sprouts.Tuple;

/**
 * Produces the SSH files and command lines used to reach the sandbox.
 *
 * <p>SSH runs over a Unix socket, never a TCP port, so the container can keep having no network.
 * Each lamp has its own key pair and a pinned host key, so the user is never asked to accept a
 * host key and their own SSH keys are never offered to the sandbox ({@code IdentitiesOnly yes}).
 */
final class Ssh {

    private Ssh() {}

    /** Which host-side socket a shell connects through. This decides whether closing it ends the session. */
    public enum SocketRole {
        /** The terminal window oillamp opened. One per session; when it closes, the session ends. */
        PRIMARY,
        /** An extra shell from {@code oillamp shell}; closing it does not end the session. */
        EXTRA
    }

    public static String renderClientConfig(LampLayout layout) {
        return """
            # Generated by oillamp — do not edit; it is rewritten at every session start.
            Host %s
              User agent
              HostName %s
              IdentityFile %s
              IdentitiesOnly yes
              UserKnownHostsFile %s
              StrictHostKeyChecking yes
              ServerAliveInterval 15
              ForwardAgent no
              ForwardX11 no
              ClearAllForwardings yes
              LogLevel ERROR
            """.formatted(
                layout.sshHostAlias(),
                layout.sshHostAlias(),
                layout.clientKey(),
                layout.knownHosts());
    }

    /** The pinned host key line, so the user is never prompted to trust the sandbox. */
    public static String renderKnownHosts(LampLayout layout, String hostPublicKey) {
        return layout.sshHostAlias() + " " + hostPublicKey.trim() + "\n";
    }

    /** The sshd configuration inside the container. The image ships the same text as {@code /etc/oillamp/sshd_config}. */
    public static String renderSshdConfig() {
        return """
            # Generated by oillamp. sshd runs per connection as the unprivileged `agent` user,
            # so it can only ever log in as that user — which is exactly what we want.
            HostKey /oillamp/session/ssh_host_ed25519_key
            AuthorizedKeysFile /oillamp/session/authorized_keys
            AllowUsers agent
            PubkeyAuthentication yes
            PasswordAuthentication no
            KbdInteractiveAuthentication no
            UsePAM no
            PermitRootLogin no
            PermitUserEnvironment no
            StrictModes no
            AllowTcpForwarding no
            AllowStreamLocalForwarding no
            AllowAgentForwarding no
            X11Forwarding no
            PermitTunnel no
            PrintMotd no
            PidFile none
            Subsystem sftp internal-sftp
            """;
    }

    /**
     * The argv that opens a shell in the sandbox.
     *
     * <p>The {@code ProxyCommand} differs per role, so it is passed on the command line, while the
     * shared settings are in the generated {@code ssh_config}.
     */
    public static Tuple<String> clientArgv(LampLayout layout, SocketRole role) {
        java.nio.file.Path socket = role == SocketRole.PRIMARY
                ? layout.primarySshSocket()
                : layout.extraSshSocket();
        return Tuple.of(String.class,
                "ssh",
                "-F", layout.sshConfig().toString(),
                "-o", "ProxyCommand=socat - UNIX-CONNECT:" + socket,
                "-t", layout.sshHostAlias(),
                "cd ~/workspace && exec bash -l");
    }

    /** SSH configuration that sends outbound SSH from inside the sandbox through the egress proxy. */
    public static String renderOutboundProxyConfig(int proxyPort) {
        return """
            # Generated by oillamp: git@github.com and friends go through the egress proxy,
            # so the policy sees `CONNECT github.com:22` like any other connection.
            Host * !lamp-*
              ProxyCommand socat - PROXY:127.0.0.1:%%h:%%p,proxyport=%d
            """.formatted(proxyPort);
    }
}
