package dev.oillamp;

import sprouts.Tuple;

/**
 * Renders the SSH client configuration and command lines — spec §17.1, Appendix D.
 *
 * <p>The sandbox is reached over a Unix socket, never a TCP port (D-08): that keeps
 * {@code --network=none} intact, so nothing on the host's network can reach the sandbox and
 * nothing in the sandbox can reach the network except through the policy proxy.
 *
 * <p>The per-lamp key pair and pinned host key mean the user is never asked to accept a host key,
 * and the user's own SSH identities are never offered to the sandbox.
 */
final class Ssh {

    private Ssh() {}

    /** Which host-side socket a shell connects through — the difference decides session lifetime. */
    public enum SocketRole {
        /**
         * The terminal window oillamp opened. Exactly one per session; when it closes, the
         * session ends (D-09, FR-06).
         */
        PRIMARY,
        /** An extra shell from {@code oillamp shell}; closing it does not end the session. */
        EXTRA
    }

    public static String renderClientConfig(LampLayout layout) {
        return """
            # Generated by oillamp — do not edit; it is rewritten at every session start.
            Host %s
              User agent
              HostName %s
              IdentityFile %s
              IdentitiesOnly yes
              UserKnownHostsFile %s
              StrictHostKeyChecking yes
              ServerAliveInterval 15
              ForwardAgent no
              ForwardX11 no
              ClearAllForwardings yes
              LogLevel ERROR
            """.formatted(
                layout.sshHostAlias(),
                layout.sshHostAlias(),
                layout.clientKey(),
                layout.knownHosts());
    }

    /** The pinned host key line, so the user is never prompted to trust the sandbox. */
    public static String renderKnownHosts(LampLayout layout, String hostPublicKey) {
        return layout.sshHostAlias() + " " + hostPublicKey.trim() + "\n";
    }

    /** The sshd configuration inside the container — Appendix D, §17.2. */
    public static String renderSshdConfig() {
        return """
            # Generated by oillamp. sshd runs per connection as the unprivileged `agent` user,
            # so it can only ever log in as that user — which is exactly what we want.
            HostKey /oillamp/session/ssh_host_ed25519_key
            AuthorizedKeysFile /oillamp/session/authorized_keys
            AllowUsers agent
            PubkeyAuthentication yes
            PasswordAuthentication no
            KbdInteractiveAuthentication no
            UsePAM no
            PermitRootLogin no
            PermitUserEnvironment no
            StrictModes no
            AllowTcpForwarding no
            AllowStreamLocalForwarding no
            AllowAgentForwarding no
            X11Forwarding no
            PermitTunnel no
            PrintMotd no
            PidFile none
            Subsystem sftp internal-sftp
            """;
    }

    /**
     * The argv that opens a shell in the sandbox.
     *
     * <p>The {@code ProxyCommand} differs per role, so it is passed on the command line while the
     * shared settings stay in the generated config file (§17.1).
     */
    public static Tuple<String> clientArgv(LampLayout layout, SocketRole role) {
        java.nio.file.Path socket = role == SocketRole.PRIMARY
                ? layout.primarySshSocket()
                : layout.extraSshSocket();
        return Tuple.of(String.class,
                "ssh",
                "-F", layout.sshConfig().toString(),
                "-o", "ProxyCommand=socat - UNIX-CONNECT:" + socket,
                "-t", layout.sshHostAlias(),
                "cd ~/workspace && exec bash -l");
    }

    /** Outbound SSH from inside the sandbox goes through the policy proxy too (§18.6). */
    public static String renderOutboundProxyConfig(int proxyPort) {
        return """
            # Generated by oillamp: git@github.com and friends go through the egress proxy,
            # so the policy sees `CONNECT github.com:22` like any other connection.
            Host * !lamp-*
              ProxyCommand socat - PROXY:127.0.0.1:%%h:%%p,proxyport=%d
            """.formatted(proxyPort);
    }
}
