package dev.oillamp;

import sprouts.Tuple;

/// Produces the SSH files and command lines used to reach the sandbox.
///
/// SSH runs over a Unix socket, never a TCP port, so the container can keep having no network.
/// Each lamp has its own key pair and a pinned host key, so the user is never asked to accept a
/// host key and their own SSH keys are never offered to the sandbox (`IdentitiesOnly yes`).
final class Ssh {

    private Ssh() {}

    /// Which host-side socket a shell connects through. Closing either ends nothing.
    public enum SocketRole {
        /// The terminal window oillamp opened. One per session; its connecting is what makes the
        /// session count as up.
        PRIMARY,
        /// An extra shell from `oillamp shell`; closing it does not end the session.
        EXTRA
    }

    public static String renderClientConfig(LampLayout layout) {
        return """
            # Generated by oillamp — do not edit; it is rewritten at every session start.
            Host %s
              User agent
              HostName %s
              IdentityFile %s
              IdentitiesOnly yes
              UserKnownHostsFile %s
              StrictHostKeyChecking yes
              ServerAliveInterval 15
              ForwardAgent no
              ForwardX11 no
              ClearAllForwardings yes
              LogLevel ERROR
            """.formatted(
                layout.sshHostAlias(),
                layout.sshHostAlias(),
                layout.clientKey(),
                layout.knownHosts());
    }

    /// The pinned host key line, so the user is never prompted to trust the sandbox.
    public static String renderKnownHosts(LampLayout layout, String hostPublicKey) {
        return layout.sshHostAlias() + " " + hostPublicKey.trim() + "\n";
    }

    /// The argv that opens a shell in the sandbox.
    ///
    /// The `ProxyCommand` differs per role, so it is passed on the command line, while the
    /// shared settings are in the generated `ssh_config`.
    public static Tuple<String> clientArgv(LampLayout layout, SocketRole role) {
        java.nio.file.Path socket = role == SocketRole.PRIMARY
                ? layout.primarySshSocket()
                : layout.extraSshSocket();
        return Tuple.of(String.class,
                "ssh",
                "-F", layout.sshConfig().toString(),
                "-o", "ProxyCommand=socat - UNIX-CONNECT:" + socket,
                "-t", layout.sshHostAlias(),
                "cd ~/workspace && exec bash -l");
    }
}
